
spring:
  #静态资源处理
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  #  thymelaef模板配置mysql
  thymeleaf:
    cache: false
    content-type: text/html
    mode: LEGACYHTML5
  #    数据源的配置
  #云服务器 mysql账号lwh pass:1234    本地:root root
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://122.112.196.252:3306/seckill?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    #    连接池的配置
    hikari:
      pool-name: DateHikariCP
      #      最小空闲连接数
      minimum-idle: 5
      #      空闲连接存活最大时间
      idle-timeout: 1800000
      #      最大连接数
      maximum-pool-size: 10
      #      从连接池返回的连接自动提交
      auto-commit: true
      #      连接最大存活时间
      max-lifetime: 1800000
      #      连接超时时间
      connection-timeout: 30000
      #      测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    host: 122.112.196.252
    port: 6379
    database: 0
    timeout: 20000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: liu990906
  #rabbitMQ
  rabbitmq:
    host: 122.112.196.252
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  main:
    allow-bean-definition-overriding: true

#      mybatis-plus配置
mybatis-plus:
#  配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  配置mybatis数据返回类型别名（默认别名是类名 ）
  type-aliases-package: com.lwh.seckill.pojo
#日志
#mybatis sql打印（方法接口所在的包，不是mapper.xml所在的包）
logging:
  level:
    com.lwh.seckill.mapper: debug
server:
  port: 8888
